version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 4035:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./dist:/var/www/html/wp-content/themes/wordpress-zero

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080

networks:
  back:

volumes:
  wordpress:
  db: